### ISSUE TITLE
Somewhat improved audio

### ISSUE THREAD

**Issue by caenn** [cmuratori/moriarty_audio#1]
I'm hardly an audio expert but I got a decent improvement in quality by running this through rx9. There's probably a good amount of headroom for further improvement, though I don't think it's possible to restore it to a point where it sounds amazing. Good luck!

https://1drv.ms/u/s!Aqt-9PzxZ3RYh5kn8zEX7dmwfRyNHQ?e=RhIU9w

**Comment by ThatScar** [comment]
Can anyone upload this somewhere that doesn't need microsoft login?

**Comment by caenn** [comment]
Oh sorry, didn't realize you needed an account to access it, here's a mirror on google drive: https://drive.google.com/file/d/1jojGHuG4mF-Ag27JjW22N7un8yPbcBjU/view?usp=sharing

**Comment by cmuratori** [comment]
I'm not sure that's enough of an improvement. The clicking is still really pronounced...

\- Casey
