### ISSUE TITLE
Lerping over corrupt data in "codec space"

### ISSUE THREAD

**Issue by sqaxomonophonen** [cmuratori/moriarty_audio#2]
Before/after (last few seconds of your sample):

https://github.com/sqaxomonophonen/World/raw/moriarty_audio_fix/test_moriarty_before.wav
https://github.com/sqaxomonophonen/World/raw/moriarty_audio_fix/test_moriarty_after.wav

I did it manually in a quick'n'dirty editor I just wrote that operates on "WORLD" speech analysis data:
https://github.com/sqaxomonophonen/World/commit/7258340fa52baae36c66dcf534d6a905eccbc326

"WORLD" can convert audio into speech analysis data, and can then convert that back to audio. The analysis data consists of 5ms frames containing f0 (fundamental frequency), spectrogram and "aperiodicity" data (not really sure what the last one is). Both f0 and spectogram are "curvy", so it makes sense to interpolate them (unlike PCM data), and that's exactly what the editor does; you can mark a corrupt range and then interpolate between endpoints.

Anyway, the editor is really bad and needs work to be useful on larger audio samples: it has no audio playback (so you can't immediately hear the results); it's hard to see where the problems are (I ended up referring to Audacity's spectrogram to see where the clicks are, because they're much more visible there); and there's no undo :-) Also, even if the editor got good, you'd still have to manually fix ~8-10 clicks per second of audio.

Here are before/after spectrograms (as shown in Audacity):
https://github.com/sqaxomonophonen/World/blob/moriarty_audio_fix/test_moriarty_spectral_before_after.png

**Comment by cmuratori** [comment]
That actually sounds pretty good, except for the sort-of scratchy tone at points... obviously the manual editing part is probably prohibitively expensive but I wonder if it could be improved/automated?

\- Casey

**Comment by sqaxomonophonen** [comment]
I can try to scale the approach up to the entire 52s sample, and maybe have results (good and/or bad) by the end of the week? It's largely unknown territory, so I can't predict how the quality and workflow is going to be.

In regards to quality, it's scary that I have to replace about 20% of the audio with interpolated data, and I suspect it's better to leave some of the "clicks" alone, rather than try to repair them. A visual analogy is to remove smudges from images by interpolating surrounding pixels; it probably works great for smudges on smooth surfaces, but if there's a smudge on an eye, it's arguably better to leave it alone, than to replace the eye with a smooth patch of skin. Similarly, in the audio domain, it's probably preferable to have something sound like an "audio problem" than a "speech disorder". The 20% roughly corresponds to how much audio I ended up replacing in my editor, but you can also easily see the "clicks" in quiet parts of the audio by zooming in on the waveform (I see about 1,000 samples of noise, with 5-6,000 samples between clicks).

Improving the workflow largely depends on how successful I am in automatically detecting clicks. If only they occurred at "integer intervals", but at least they're semi-regular, with intervals varying between 100-120ms. But I think I'll focus mostly on the quality, because if it's not good enough, there's no point in continuing.

**Comment by sqaxomonophonen** [comment]
Results (good and/or bad): https://github.com/sqaxomonophonen/World/raw/moriarty_audio_fix/mm_left.wav.render.wav

The audio is synthesized in a "oscillator through filter" kind of way, so obviously it struggles when you're both talking (and also in a few other places?). It would be possible to crossfade back to the "orignal" broken audio, but I haven't done it in the audio clip.

The approach only works in mono (synth only works in mono, and 2 left/right instances produces a flanger/chorus effect)

 The 52s of audio required ~130 manual edits at irregular intervals, and of varying widths. Example: https://raw.githubusercontent.com/sqaxomonophonen/World/moriarty_audio_fix/vpf.png . Red vertical lines are "marked as broken" and lerped over. Could it be automated? There are some telltale signs in the data, but sometimes I widened edits until it sounded good.

If you want to play with the software yourself: https://github.com/sqaxomonophonen/World/tree/moriarty_audio_fix . It depends on SDL2 and `mmap()`, and builds on Linux. It's also great for making funny noises.

**Comment by cmuratori** [comment]
After listening closely to this vs. the Izodope version, I felt like the Izodope version was cleaner (slightly), and it is automated... thanks for trying this out, though!

- Casey

**Comment by sqaxomonophonen** [comment]
No problem, it was a fun diversion and the things I learned might come in handy in the future. And FWIW, I also agree the iZotope version is better, all things considered. I look forward to hearing the interviews! -Anders
