### ISSUE TITLE
Try https://podcast.adobe.com/enhance

### ISSUE THREAD

**Issue by yeradis** [cmuratori/moriarty_audio#3]
Just tried https://podcast.adobe.com/enhance with the sample audio in this repo and this is the result:

[moriarty_sample (enhanced).wav.zip](https://github.com/cmuratori/moriarty_audio/files/10497136/moriarty_sample.enhanced.wav.zip)

**Comment by cmuratori** [comment]
That basically sounds the same to me? All the artifacts sounds like they are still there...

\- Casey
