### ISSUE TITLE
iZotope RX 6 Advance Audio Editor - De-click

### ISSUE THREAD

**Issue by hdorio** [cmuratori/moriarty_audio#4]
This is the output of iZotope's De-click effect
preset: Random Discontinuity
sensitivity: 6.0
click widening: 4.0 ms
[moriarty_sample_izotope_de-click.wav.zip](https://github.com/cmuratori/moriarty_audio/files/10514681/moriarty_sample_izotope_de-click.wav.zip)

Not perfect but no manual editing was needed.

**Comment by cmuratori** [comment]
This is what we ended up going with. Thekla's audio team processed the entire audio with it, and it's "usable", although not great.

- Casey
